# Generated by Django 5.0.6 on 2024-06-09 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_message', models.TextField(max_length=500)),
                ('reply_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='feedbacks.feedback')),
            ],
        ),
    ]
