# Generated by Django 5.0.6 on 2024-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expired_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
