# Generated by Django 5.0.6 on 2024-06-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_expired_at'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
