# Generated by Django 5.0.6 on 2024-06-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_remove_coupon_created_at_remove_coupon_expired_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
    ]
