# Generated by Django 5.0.6 on 2024-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
