# Generated by Django 5.0.6 on 2024-06-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='used_at',
            field=models.DateTimeField(null=True),
        ),
    ]
