# Generated by Django 5.0.6 on 2024-05-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagememos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
