# Generated by Django 5.0.6 on 2024-05-24 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagememos', '0002_alter_messagemodel_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
