# Generated by Django 5.0.6 on 2024-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('payment_fail', 'Payment Fail'), ('waiting_for_shipment', 'Waiting for shipment'), ('transporting', 'Transporting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=100)),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
            },
        ),
    ]
