# Generated by Django 5.0.6 on 2024-06-12 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('item_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('pick_up', '自取'), ('home_delivery', '宅配到府')], default='home_delivery', max_length=20)),
                ('payment_method', models.CharField(choices=[('ECPay', '綠界支付'), ('line_pay', 'LINE PAY')], default='credit_card', max_length=20)),
                ('coupon_used', models.BooleanField(default=False)),
                ('store_name', models.CharField(blank=True, max_length=100)),
                ('store_address', models.CharField(blank=True, max_length=200)),
                ('order_name', models.CharField(max_length=50)),
                ('order_cell_phone', models.CharField(max_length=10)),
                ('order_address', models.CharField(blank=True, max_length=200)),
                ('order_email', models.EmailField(max_length=50)),
                ('recipient_name', models.CharField(max_length=50)),
                ('recipient_cell_phone', models.CharField(max_length=10)),
                ('recipient_address', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(max_length=50)),
                ('return_agreement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('payment_fail', 'Payment Fail'), ('waiting_for_shipment', 'Waiting for shipment'), ('transporting', 'Transporting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=100)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
