# Generated by Django 5.0.6 on 2024-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0002_relationalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='order_set', through='store.RelationalProduct', to='store.product'),
        ),
    ]
