# Generated by Django 5.0.6 on 2024-06-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='used_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coupon', to='accounts.usercoupon'),
        ),
        migrations.AlterField(
            model_name='ordermethod',
            name='payment_method',
            field=models.CharField(choices=[('ECPay', '綠界支付'), ('line_pay', 'LINE Pay')], default='ECPay', max_length=20),
        ),
    ]
