# Generated by Django 5.0.6 on 2024-06-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_total',
            field=models.IntegerField(default=0),
        ),
    ]
