# Generated by Django 5.0.6 on 2024-05-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermethod',
            old_name='order_phone',
            new_name='order_address',
        ),
        migrations.AddField(
            model_name='ordermethod',
            name='recipient_address',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
