# Generated by Django 5.0.6 on 2024-05-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_order_phone_ordermethod_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermethod',
            name='delivery_method',
            field=models.CharField(choices=[('超商取貨', '超商取貨'), ('宅配到府', '宅配到府')], default='宅配到府', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermethod',
            name='order_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ordermethod',
            name='payment_method',
            field=models.CharField(choices=[('超商取貨付款', '超商取貨付款'), ('信用卡', '信用卡'), ('第三方支付', '第三方支付'), ('ATM 轉帳付款', 'ATM 轉帳付款')], default='信用卡', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermethod',
            name='recipient_address',
            field=models.CharField(max_length=200),
        ),
    ]
