# Generated by Django 5.0.6 on 2024-05-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
    ]
