# Generated by Django 5.0.6 on 2024-06-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordermethod_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermethod',
            name='delivery_method',
            field=models.CharField(choices=[('pick_up', '自取'), ('home_delivery', '宅配到府')], default='home_delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermethod',
            name='invoice_option',
            field=models.CharField(choices=[('donate_invoice', '捐贈發票'), ('two_invoice', '二聯式電子發票'), ('three_invoice', '三聯式電子發票')], default='donate_invoice', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermethod',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', '信用卡'), ('line_pay', 'LINE PAY'), ('atm', 'ATM 轉帳付款')], default='credit_card', max_length=20),
        ),
    ]
