# Generated by Django 5.0.6 on 2024-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_ordermethod_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermethod',
            name='store_address',
            field=models.CharField(blank=True, default='10046 台北市中正區衡陽路 7 號 5 樓', max_length=200),
        ),
    ]
