# Generated by Django 5.0.6 on 2024-06-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_ordermethod_delivery_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermethod',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='ordermethod',
            name='invoice_option',
        ),
    ]
