# Generated by Django 5.0.6 on 2024-06-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_ordermethod_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermethod',
            name='coupon_used',
        ),
        migrations.RemoveField(
            model_name='ordermethod',
            name='invoice_number',
        ),
    ]
