# Generated by Django 5.0.6 on 2024-05-20 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('shipping_address', models.CharField(max_length=200)),
                ('amount_paid', models.IntegerField()),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('超商取貨', '超商取貨'), ('宅配到府', '宅配到府')], max_length=20)),
                ('payment_method', models.CharField(choices=[('超商取貨付款', '超商取貨付款'), ('信用卡', '信用卡'), ('第三方支付', '第三方支付'), ('ATM 轉帳付款', 'ATM 轉帳付款')], max_length=20)),
                ('coupon_used', models.BooleanField(default=False)),
                ('store_name', models.CharField(blank=True, max_length=100)),
                ('store_address', models.CharField(blank=True, max_length=200)),
                ('order_name', models.CharField(max_length=50)),
                ('order_cell_phone', models.CharField(max_length=10)),
                ('order_phone', models.CharField(blank=True, max_length=10)),
                ('order_email', models.EmailField(max_length=50)),
                ('recipient_name', models.CharField(max_length=50)),
                ('recipient_cell_phone', models.CharField(max_length=10)),
                ('recipient_email', models.EmailField(max_length=50)),
                ('invoice_option', models.CharField(choices=[('捐贈發票', '捐贈發票'), ('二聯式電子發票', '二聯式電子發票'), ('三聯式電子發票', '三聯式電子發票')], max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=8, null=True)),
                ('return_agreement', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
