# Generated by Django 5.0.6 on 2024-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermethod',
            name='delivery_method',
            field=models.CharField(choices=[('超商取貨', '超商取貨'), ('宅配到府', '宅配到府')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermethod',
            name='invoice_option',
            field=models.CharField(choices=[('捐贈發票', '捐贈發票'), ('二聯式電子發票', '二聯式電子發票'), ('三聯式電子發票', '三聯式電子發票')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermethod',
            name='payment_method',
            field=models.CharField(choices=[('超商取貨付款', '超商取貨付款'), ('信用卡', '信用卡'), ('第三方支付', '第三方支付'), ('ATM 轉帳付款', 'ATM 轉帳付款')], max_length=20),
        ),
    ]
